### ISSUE TITLE
rails npm:install on Ubuntu WSL gets: Error: EACCES: permission denied, mkdir '/mnt/c/Users/Amadeus' TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by amadeuspagel** [endenwer/npm-rails#11]
This is the full error:

```
/home/amadeus/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/app_loader.rb:53: warning: Insecure world writable dir /home/amadeus/.rbenv/versions in PATH, mode 040777
npm install --prefix /mnt/c/Users/Amadeus Pagel/Documents/readpaths --loglevel error cytoscape@"latest" cytoscape-popper@"latest"
Error: EACCES: permission denied, mkdir '/mnt/c/Users/Amadeus'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:224:22)
    at /usr/lib/node_modules/npm/lib/npm.js:262:24
    at /usr/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:178:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:234:20)
    at /usr/lib/node_modules/npm/lib/config/set-user.js:23:20
    at /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53
    at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:378:26)
rails aborted!
Command failed with status (7): [npm install --prefix /mnt/c/Users/Amadeus ...]
/mnt/c/Users/Amadeus Pagel/Documents/readpaths/bin/rails:9:in `require'
/mnt/c/Users/Amadeus Pagel/Documents/readpaths/bin/rails:9:in `<top (required)>'
/mnt/c/Users/Amadeus Pagel/Documents/readpaths/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => npm:install
```

**Comment by endenwer** [comment]
Rails now support js packages. You can use https://github.com/rails/webpacker
